version: '3'

services:
  recipes_drawer_backend:
    container_name: recipes-drawer-backend
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 9000 -b '0.0.0.0'"
    ports:
      - 9000:9000
    environment:
      - CONTENTFUL_SPACE_ID=
      - CONTENTFUL_ENVIRONMENT_ID=
      - CONTENTFUL_DELIVERY_TOKEN=
      - CONTENTFUL_API_URL=